# Generated by Django 4.1.2 on 2025-03-09 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('not_filled', 'Not Filled'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_filled', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('land_area', models.FloatField(default=0.0, help_text='Land area in hectares')),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('farming_practices', models.CharField(blank=True, choices=[('organic', 'Organic'), ('conventional', 'Conventional')], max_length=100, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation_method', models.CharField(blank=True, choices=[('drip', 'Drip'), ('flood', 'Flood'), ('sprinkler', 'Sprinkler')], max_length=100, null=True)),
                ('fertilizer_usage', models.CharField(blank=True, choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=100, null=True)),
                ('cover_crops', models.BooleanField(default=False)),
                ('tillage_practices', models.CharField(blank=True, choices=[('no-till', 'No Till'), ('minimum-till', 'Minimum Till'), ('conventional-till', 'Conventional Till')], max_length=100, null=True)),
                ('carbon_credits', models.FloatField(default=0.0)),
                ('monetary_benefit', models.FloatField(default=0.0)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
